# Generated by Django 4.2.15 on 2025-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_types', '0007_delete_relationtypeold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='text',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='text',
            field=models.CharField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='spantype',
            name='text',
            field=models.CharField(db_index=True, max_length=400),
        ),
    ]
